server.port=8080
spring.application.name=clyvovet
spring.jackson.serialization.write-dates-as-timestamps=false

spring.datasource.url=jdbc:h2:tcp://clyvovet-db:1521/clyvovet
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true