# Nome da aplicação
spring.application.name=clyvovet

# Perfil ativo - estamos em desenvolvimento
spring.profiles.active=dev

# Porta do servidor
server.port=8080

# Formata datas como ISO-8601 em vez de números (timestamps)
spring.jackson.serialization.write-dates-as-timestamps=false